name: Module/Code Adaptation
description: Propose adaptation of existing cisco.ios logic to eltex.mes
title: "[Adaptation]: "
body:
  - type: input
    id: target
    attributes:
      label: Target component
      placeholder: "module, action plugin, facts, connection, documentation section, etc."
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary of adaptation
      placeholder: |
        What was adapted:
        - module X from cisco.ios → eltex.mes
        - replaced Y logic
        - updated parameters / mapping
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: Upstream references
      placeholder: |
      Provide links, e.g.:
        - vendor documentation
        - TODO
        - related issues or PRs
        - discussion with details
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Technical approach
      placeholder: |
        Describe:
        - what exactly you ported
        - what you changed for MES syntax/behavior
        - what you intentionally did NOT port and why
        - CLI examples if relevant
      render: shell
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing / Verification
      placeholder: |
        Include:
        - playbook snippet used for testing
        - raw device CLI output (sanitized)
        - before/after changes
      render: shell
    validations:
      required: true

  - type: textarea
    id: compatibility
    attributes:
      label: Compatibility notes (if any)
      placeholder: |
        Explain behavior differences vs cisco.ios:
        - parameters removed/added
        - idempotency differences
        - known device OS quirks
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Code follows Ansible Collections guidelines
        - label: Idempotency verified
        - label: Code tested
        - label: Documentation updated
