name: Quick Fix
description: Small bugfix or typo correction
title: "[Fix]: "
body:
  - type: textarea
    id: summary
    attributes:
      label: What was fixed?
      placeholder: "Short explanation"
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing / Verification
      description: "How did you verify the fix or reproduce the issue? Include exact commands/playbooks and device context."
      placeholder: |
        Example:
        - Environment: MES3324F (FW 6.6.2), Ansible 2.16, Python 3.13
        - Repro/verify steps:
          ansible-playbook playbooks/mes_check.yml -i inventory.ini -l mes3324f-01
        - Expected vs actual CLI/output:
          show running-config
          show interfaces status
      render: shell
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: No behavior change except the fix
        - label: Linted (ansible-lint/flake8) and basic tests pass
        - label: Playbook/examples run without errors on target device(s)
        - label: Docs/README updated if behavior or usage changed
