name: Pull Request
description: Standard pull request
title: "[PR]: "
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: "What this PR changes"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Context
      placeholder: "Why this change is needed"
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Detailed changes
      placeholder: |
        - Added …
        - Updated …
        - Fixed …
    validations:
      required: false

  - type: textarea
    id: testing
    attributes:
      label: Testing
      placeholder: |
        Commands, logs, steps performed
      render: shell
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Code builds and passes linters
        - label: Tests added/updated
        - label: Documentation updated
        - label: No breaking changes without justification
