---
authors:
  - Ansible Network Community (ansible-network)
  - Nikita Mishagin
dependencies:
  "ansible.netcommon": ">=8.1.0"
license_file: LICENSE
name: mes
namespace: nikitamishagin
description: Ansible Network Collection for Eltex MES devices.
readme: README.md
repository: https://github.com/nikitamishagin/ansible_eltex
issues: https://github.com/nikitamishagin/ansible_eltex/issues
tags: [eltex, mes, networking]
version: "0.0.1"
